openapi: 3.0.0
info:
  title: My Express API
  version: 1.0.0
paths:
  /api:
    get:
      summary: Get data with a parameter
      parameters:
        - in: query
          name: parameterName
          schema:
            type: string
          required: true
          description: The parameter you need to provide.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Bad Request